---
server:
    host: "0.0.0.0"
    port: 2112
    uri: "/metrics"
    scrappingInterval: "15m"
    logName: "nbu-exporter.log"
nbuserver:
    scheme: "https"
    uri: "/netbackup"
    domain: "NBU_WOW"
    domainType: "NT"
    host: "10.4.160.96"
    port: 1556
    apiKey: "uglg;9876543wefghjkjhgfvdcs=="
    contentType: "application/vnd.netbackup+json; version=3.0"